name: drtshock

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/drtshock.yml'
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  uses: HSGamer/ConstructProjects/.github/workflows/maven-build.yml@main
  with:
    repository: "drtshock/PlayerVaults"
    target: "target/*"
    name: "PlayerVaults"
    java: 17
