name: ds58

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/ds58.yml'
  schedule:
    - cron: '0 0 * * *'

jobs:
  Panilla:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "ds58/Panilla"
      name: "Panilla"
      target: "target/**/*.jar"
      java: |
        8
        16
        17
      commands: |
        curl -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        JAVA_HOME_8="JAVA_HOME_8_${RUNNER_ARCH}"
        JAVA_HOME_16="JAVA_HOME_16_${RUNNER_ARCH}"
        JAVA_HOME_17="JAVA_HOME_17_${RUNNER_ARCH}"
        "${!JAVA_HOME_8}"/bin/java -jar BuildTools.jar --rev 1.8.8 --compile craftbukkit
        "${!JAVA_HOME_8}"/bin/java -jar BuildTools.jar --rev 1.12.2 --compile craftbukkit
        "${!JAVA_HOME_8}"/bin/java -jar BuildTools.jar --rev 1.13.2 --compile craftbukkit
        "${!JAVA_HOME_8}"/bin/java -jar BuildTools.jar --rev 1.14.4 --compile craftbukkit
        "${!JAVA_HOME_8}"/bin/java -jar BuildTools.jar --rev 1.15 --compile craftbukkit
        "${!JAVA_HOME_8}"/bin/java -jar BuildTools.jar --rev 1.16.1
        "${!JAVA_HOME_8}"/bin/java -jar BuildTools.jar --rev 1.16.2
        "${!JAVA_HOME_8}"/bin/java -jar BuildTools.jar --rev 1.16.4
        "${!JAVA_HOME_16}"/bin/java -jar BuildTools.jar --rev 1.17
        "${!JAVA_HOME_17}"/bin/java -jar BuildTools.jar --rev 1.18
        "${!JAVA_HOME_17}"/bin/java -jar BuildTools.jar --rev 1.18.2
        "${!JAVA_HOME_17}"/bin/java -jar BuildTools.jar --rev 1.19.2
        "${!JAVA_HOME_17}"/bin/java -jar BuildTools.jar --rev 1.19.3
        "${!JAVA_HOME_17}"/bin/java -jar BuildTools.jar --rev 1.19.4
        "${!JAVA_HOME_17}"/bin/java -jar BuildTools.jar --rev 1.20
        "${!JAVA_HOME_17}"/bin/java -jar BuildTools.jar --rev 1.20.2
        "${!JAVA_HOME_17}"/bin/java -jar BuildTools.jar --rev 1.20.4
