name: Gradle Build
on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      target:
        default: 'build/libs/*.jar'
        required: false
        type: string
      name:
        default: 'Artifact'
        required: false
        type: string
      commands:
        default: 'echo Nothing here'
        required: false
        type: string
      java:
        default: '16'
        required: false
        type: string
      distribution:
        default: 'temurin'
        required: false
        type: string
      os:
        default: 'ubuntu-latest'
        required: false
        type: string
      tasks:
        default: 'build'
        required: false
        type: string
      buildtools:
        default: false
        required: false
        type: boolean
      versions:
        default: "latest"
        required: false
        type: string
jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
    - name: Set up JDK
      uses: actions/setup-java@v3.6.0
      with:
        java-version: ${{ inputs.java }}
        distribution: ${{ inputs.distribution }}
        cache: gradle
    - name: Run BuildTools
      if: ${{ inputs.buildtools }}
      uses: SpraxDev/Action-SpigotMC@v4
      with:
        versions: ${{ inputs.versions }}
        generateSrc: false
        generateDoc: false
        disableJavaCheck: false
        remapped: false
        forceRun: false
        threads: -1
        buildToolProvider: SpigotMC
    - name: Run prebuild commands
      run: ${{ inputs.commands }}
    - name: Grant permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew ${{ inputs.tasks }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.target }}
