name: IntellectualSites

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/IntellectualSites.yml'
  schedule:
    - cron: '0 */12 * * *'

jobs:
  PlotSquared:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "IntellectualSites/PlotSquared"
      name: "PlotSquared"
      target: "Bukkit/build/libs/*.jar"
