name: Photon

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/Photon.yml'
  schedule:
    - cron: '0 0 * * *'

jobs:
  AntiCheatAddition:
    uses: HSGamer/ConstructProjects/.github/workflows/maven-build.yml@main
    with:
      repository: "Photon-GitHub/AntiCheatAddition"
      name: "AntiCheatAddition"
      java: 17
      tasks: "clean package -DskipTests"
