name: Pyrbu

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/Pyrbu.yml'
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  ZNPCsPlus:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Pyrbu/ZNPCsPlus"
      name: "ZNPCsPlus"
      java: "17"
      target: "plugin/build/libs/*.jar"
