name: VolmitSoftware

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/VolmitSoftware.yml'
  schedule:
    - cron: '0 0 * * *'

jobs:
  Iris:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "VolmitSoftware/Iris"
      name: "Iris"
      java: "17"
      commands: |
        curl -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        JAVA_HOME_17="JAVA_HOME_17_${RUNNER_ARCH}"
        "${!JAVA_HOME_17}"/bin/java -jar BuildTools.jar --rev 1.19.2 --compile craftbukkit --remapped
        "${!JAVA_HOME_17}"/bin/java -jar BuildTools.jar --rev 1.19.3 --compile craftbukkit --remapped
        "${!JAVA_HOME_17}"/bin/java -jar BuildTools.jar --rev 1.19.4 --compile craftbukkit --remapped
        "${!JAVA_HOME_17}"/bin/java -jar BuildTools.jar --rev 1.20.1 --compile craftbukkit --remapped
        "${!JAVA_HOME_17}"/bin/java -jar BuildTools.jar --rev 1.20.2 --compile craftbukkit --remapped
        "${!JAVA_HOME_17}"/bin/java -jar BuildTools.jar --rev 1.20.4 --compile craftbukkit --remapped
  Adapt:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "VolmitSoftware/Adapt"
      name: "Adapt"
      java: "17"
  React:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "VolmitSoftware/React"
      name: "React"
      java: "17"
      tasks: "shadowJar"
      dir: "React"
      target: "React/build/libs/*.jar"
